### ISSUE TITLE
Allow users to select correct gym when screenshot matches more than one in the DB

### ISSUE THREAD

**Issue by bradders2000** [PokeNavBot/issue-tracker#130]
When the gym name on a screenshot matches 2 or more gyms in the database for the given location (even when set to 10km radius, it does happen!), print out the options in the dedicated channel and allow the user to pick which one is correct. By that I mean in the same way it lets you if you try to set it manually via $gym.

**Comment by fortepc** [comment]
_Copying my post to here as the issues are similar enough to just be merged. _ 

When a user reports a raid, and the bot is unable to pair it to a specific gym due to duplicate gyms, it should prompt the user (with a tag) in the reporting channel to identify which gym they're reporting that raid for.

**Comment by Kdog0073** [comment]
For more detail, currently, users need to type in $gym starbucks to get the bot to ask which starbucks it is. Because of this, many users will post one of these gyms, but often not know to update the location. This means that the raid also will not appear on the app.

If the bot detects that the gym text could refer to multiple locations, it would be better user experience if the prompt asking for which gym automatically pops up, rather than a user needing to type $gym

**Comment by TheGerontocracy** [comment]
We also have the same issue for quests. Players don't get any notification that the screenshot cannot be matched to a unique pokestop. We waist a lot of time correcting quests because of this missing feature.

**Comment by dandesousa** [comment]
So I am inclined to add this soon -- what I am thinking is that if there is a duplicate, before it creates the raid, it would display the dialogue. If it cannot create the raid because the person doesn't specify the right one, it will make one without a linked gym (the way it does now) with the timeout set to something reasonably short, like 20-30 seconds. Would apply to both research and raids.

**Comment by Hasensuppe** [comment]
most users on our server do not notice the missing map link if gym name has dublicates. therefor it is an ongoing issue especially since two important ex gyms have a dublicate. The suggested fix would be highly appreciated.

**Comment by dandesousa** [comment]
bump

**Comment by mikosoby** [comment]
One addition/improvement from the discussion in the #feature-requests channel.
After the bot fails to determine to correct PoI_(because of the duplicate names or PoI not being in the database)_ the reporter should be tagged to correct/pair it also with the list of possible PoIs and the last option should be the "Gym/PokéStop not listed", this option would tag the Raid Moderator/Research Moderator so they are reminded to create the new PoI.
Also in case the reporter doesn't correct/pair the PoI in the time limit(30-60 seconds?) the Moderators should also be tagged to solve the issue.
