### ISSUE TITLE
Allow users to update their friend code by posting a screenshot of their QR code

### ISSUE THREAD

**Issue by fortepc** [PokeNavBot/issue-tracker#141]
As the title suggests, in the profile team assignment room allow the bot to recognize that there is a QR code in the screenshot and set their trainer code based on that QR code.

**Comment by Kdog0073** [comment]
For this, I think there is a simpler way. Rather than store the QR code, it can grab the username and friend code right off the screen. This can store the IGN (as of writing, storing IGN would be a new profile field) if it is not set already, and update the friend code.

In addition, since this is a way to get IGN, it would be nice if it can try to look up the other linkages like the silph card or trainerdex. It could be automatic, or a prompt such as "sil.ph/kdog0073 found, would you like to link it?".

Additional consideration: allow the discord user to upload multiple, specifying a main. Similarly to how a user can set the raid join to automatically add additional team members, some discord users have, for example, significant other or kid accounts.

As a byproduct, "$trainer [ign]" should allow us to look up a user by IGN
