### ISSUE TITLE
If Gym Lookup Fails due to Duplicate Possible Gyms, prompt user to update report

### ISSUE THREAD

**Issue by fortepc** [PokeNavBot/Issue-Tracker#149]
When a user reports a raid, and the bot is unable to pair it to a specific gym due to duplicate gyms, it should prompt the user (with a tag) in the reporting channel to identify which gym they're reporting that raid for.

**Comment by bradders2000** [comment]
very similar to #130

**Comment by fortepc** [comment]
Agreed, the two issues should probably be merged

**Comment by dandesousa** [comment]
Duplicate #130

**Comment by Kdog0073** [comment]
For more detail, currently, users need to type in $gym starbucks to get the bot to ask which starbucks it is. Because of this, many users will post one of these gyms, but often not know to update the location. This means that the raid also will not appear on the app.

If the bot detects that the gym text could refer to multiple locations, it would be better user experience if the prompt asking for which gym automatically pops up, rather than a user needing to type $gym
