### ISSUE TITLE
When Gym is not able to be matched, have the first set of messages include a prompt for someone to update the location

### ISSUE THREAD

**Issue by fortepc** [PokeNavBot/issue-tracker#150]
Have the bot specifically say ```This raid is not linked to a gym, please use the $gym command to link this raid to a specific gym so I know where it is and can help other Trainers find it``` for every raid party it creates that doesn't have a gym properly linked to it, and if the gym gets linked after, this message should be deleted to avoid confusion.

**Comment by sunkast** [comment]
I second this. I have a similar situation where there is a gym at 2 different post offices that are both named "City Post Office." PokeNav creates a raid, but never assigns a location due to the gym matching more than one location, thus never appearing in the companion app. A follow up prompt, similar to when you search for a gym and it returns more than 1 match would be helpful. Otherwise members have to be conscious that the raid will not appear in the app unless they manually update the location for the raid.

**Comment by enanox** [comment]
Indeed, unless we (as Go players) can ascertain a way to fix duplicate POI names without messing the portal > gym map rendering, it's a minor nuisance we are facing.

I have it with some gyms on my nearby, "Mural" and "Wilson Ferreira Aldunate" (on two different neighborhoods, with the same capitalization and such) .

**Comment by fortepc** [comment]
I would like to follow up since this has been recently referenced and say that I have a different way I would prefer this be done. I would like the bot to be proactive about this, in the announce raids here channel it should specifically respond to the raid report tagging the reporter give the same prompt that $gym would give, say hey, I recognize that gym name to match multiple gyms, which one are you reporting.

**Comment by dandesousa** [comment]
The way I think I will implement this is actually potentially in reverse...instead of preventing the generation of the raid it would generate the raid without a link, then ask the user to de-duplicate (in the same channel as has been suggested here and by others for other types of POI linking actions). The reason is that most of the cost of creating the raid has already been done by the time a duplicate has been detected (OCR may have been performed -- database lookups done) and if a user doesn't respond, you effectively throw that away (including the quota used to get the gym name). 

So maybe it makes the raid, then starts a follow up interactive session to clarify and will update it if the user responds, otherwise it remains in the state it was in. 

It might also be a good chance to introduce some metadata into raid reports that remembers that its a duplicate and a simplified command you can call up in channel to deduplicate like `$gym` with no arguments which might check to see if it is unlinked with dups and shows the options.

**Comment by dandesousa** [comment]
This can be apart of https://github.com/PokeNavBot/issue-tracker/issues/130
