### ISSUE TITLE
Third-Party-Submission-System/API

### ISSUE THREAD

**Issue by dotbanana** [PokeNavBot/issue-tracker#185]
With a Third-Party-Submission-System we could easily use our own infrastructure/ressources to do the OCR'ing and implement raid-data from other systems like Telegram into the PokeNav-Database without doing tedious bot-2-bot-communication in discord.

**Comment by fortepc** [comment]
One potential issue with this, is giving people the ability to fuel the bot with bot account scanners if they ever come back.

PokeNav is great because it's a TOS friendly raid map, getting it tainted with bad data isn't something in excited about

**Comment by fortepc** [comment]
This concern is exactly why Meowth bot doesn't allow receiving raid reports from bots at all.

**Comment by dandesousa** [comment]
Technically you could still get reports into meowth or pokenav if you wanted -- by making a self-bot account that reposts raid reports from a scanner. Technically self-bots are also against discord TOS ... but for the determined it is possible. Sort of lean that there should be a balance between what the tool enables and the ability of people to use only what they want.

One such compromise could be a piece of metadata that comes from the reporter or PokeNav itself about whether it came from a third party report; then people and servers could choose to hide third party reports if they wanted.

I might wait for more use cases on this since dot banana went with elm for now. One such possible use case would be to get other raid bots reporting into the PokeNav app and starting raids in PokeNav from other reports, but those types of integrations are ones I'm still reaching out to other bot developers about.

**Comment by dandesousa** [comment]
Closing this to reduce noise -- no one has requested otherwise and this is already possible through Webhooks / bot 2 bot which provides an interface already compatible with user reporting (and is in use through miscord)
