### ISSUE TITLE
Channel modifier for create raid notifications

### ISSUE THREAD

**Issue by kanmpk** [PokeNavBot/Issue-Tracker#196]
**Is your feature request related to a problem? Please describe.** Yes, the ability to add channel as a modifier for raid notifications due to radius does not suit some areas that have area channel splits.

**Describe the solution you'd like**
A channel modifier. channel: #channelname - matches any raid posted in this channel

**Describe alternatives you've considered**
Tried adding gyms manually but i have several servers to update for this feature which would take days just to sort the gym names out for each area channel per server.

**Additional context**

**Comment by dandesousa** [comment]
This is a great suggestion

**Comment by kanmpk** [comment]
I did comment it in #feature requests but i know your super busy and may have missed it with all the others posted

**Comment by dandesousa** [comment]
Truth is, the best way to get me to work on something is to post here -- if you post in #feature-requests, I need to read through a huge backlog, then I usually end up making the tickets, so when I'm busy I usually just look on the GitHub for things to do. When I get free time I will read through feature-requests so as not to be overly distract from what I'm working on. Plus because I am actually currently working on changes to modifiers, I am likely to work on this feature immediatelly -- hence the benefit of having it organize in GitHub (better visibility).

**Comment by fortepc** [comment]
I was actually planning on requesting the same thing 😁
