### ISSUE TITLE
Command to track the start time of a raid separately from $status

### ISSUE THREAD

**Issue by dandesousa** [PokeNavBot/Issue-Tracker#24]

**Comment by fortepc** [comment]
I'll start by copy pasting my idea I posted on #12 being unintentionally off topic and derailing that thread.

`$hatch set 44`  -- sets 44 minutes to hatch 1:29 minutes to despawn
`$despawn set 33` -- sets hatch to 0, 0:33 minutes to despawn
`$timer set 22` -- if the channel is labeled as an egg currently it treats it like a `$hatchset`, if it's currently a known raid boss it treats it like a `$despawnset`.
`$starttime set 18` -- sets the raid start time to 18 minutes away. If the raid will still be an egg at that time it gives an error.
`$starttime set 5:40pm` -- sets the raid's scheduled start time to 5:40pm

`$hatch` -- returns the time remaining until it hatches, as well as the specific time it will hatch
`$despawn` -- returns the timer remaining until it despawns, as well as the specific time it will despawn
`$timer` -- returns whatever the next timer to expire is. If the egg hasn't hatched yet it returns the egg's timer, if the egg has hatched, and there is a scheduled start time, it returns that, if the scheduled start time has passed, or there is no scheduled start time then it returns the despawn time.
`$starttime` -- returns the timer remaining until scheduled start time, as well as the specific scheduled start time

**Comment by fortepc** [comment]
And now picking up from my slight derailment and to your comment over on #12

I personally like making the `set` a modifier to the same command used to retrieve information. To me that feels more natural. Lets you use the same command, and if a user tries to retrieve the info it says "no one has given me this info, use `$info set []` to give it to me, or if the user makes a mistake and leaves it out like for example they type `$hatch 34` the bot recognize what they were trying to do, but can then respond directing the user to use the correct command syntax. It would only take a couple times for the user to get it as it's very intuitive. And intuitive is way more important than less typing. 

Specifically touching on your bit about less typing is better, the part that is the most important about being less typing is the first section with the `$` attached to it, as if you try to use autocomplete on most phones it adds a space between the symbol and the word. Plus, autocomplete will quickly adapt to the user and everytime they type `$hatch` the keyboard would start recommending they type `set`. 

I've been using meowth primarily in my servers, and the addition of the one letter command aliases has been great to how easy the commands are to type even with typing out the whole gym name and such. `!r 5 The Wildest Roundest Ball of Lightning 34` is still easy to type because of autocomplete or even voice typing on mobile.

**Comment by dandesousa** [comment]
PokeNav does have single letter and shortened aliases and more are coming -- I add them as suggested or as I see common commands used frequently -- patch releasing tonight has a number of new ones.

Also I've never had my keyboard autocomplete ever attempt to predict my bot commands in over a year of using discord (iPhone google and apple keyboards) but no pokenav or momo (which we use in my server) or the bot that proceeded pokenav a year ago in our server have commands are multi word. I think auto complete statement makes an assumption which is not true for as many users as you think.

`info set value` is predictable, but its not any more intuitive than write only or read only commands, since you have to know the command in the first place to set it or retrieve it. I still need to know `hatch` or `despawn` as a command, and if I know it I shouldn't need to also say `set` if I provide it a value. 🤷‍♂️ Arguable its not any different than adopting a convention of `$set-hatch 34` and `$hatch => 34` or `$hatch 34 (write)` `$hatch (read) => 34`. Its just consistency and predictability, which is a good thing and what I want to try to strive towards. Consistency is key.

Easy to remember and type increases usage, something I've empiraclly observed since PokeNav adopted screenshot scans as a feature, which require no typing at all (and constitute a vast majority of raid announcements).

**Comment by dandesousa** [comment]
I believe most of this was addressed and the rest is duplicate of #109
