### ISSUE TITLE
Raid announcement reaction for attending

### ISSUE THREAD

**Issue by Citnas** [PokeNavBot/issue-tracker#288]
So I don't have raid announcements set to open a new chat, I have it so it posts in the same channel it's announced in.

I'm wondering if there's a way to add an extra icon to the edit and delete reactions to allow people to say they're coming to that raid?

Like the $here command but just a reaction on the raid announcement for someone to say they'll be attending.

We don't want the new chats that get created we just want a button on the raid post that's like a tick to say yes to it.

**Comment by dandesousa** [comment]
Theres no concept of "members" without a channel at the moment; i.e. PokeNav only tracks who is at the raid if they are also in the channel. So this feature is actually more expansive than just an emoji for here. Here is meant to represent on-site arrival, not coming / interested / member.

I don't plan on changing this requirement because I believe leaving a channel out of the coordination process hurts the ability to coordinate raid groups and doesn't scale up to a large number of people.

There are some other bots that do track raid attendance without a channel. DeliBot comes to mind. Hope this helps.
