### ISSUE TITLE
Pinned message containing all friendship codes

### ISSUE THREAD

**Issue by H2thaP** [PokeNavBot/issue-tracker#299]
For new players in our community it's a struggle to find all available friendshipcodes; they'd have to use '$gtc' numerous times. Which is annoying to them, flooding the channel they are in and it's spamming the bot.

It would be perfect if the bot would maintain an pinned message in a selected channel containing all friendship codes of the players in that community. Every time someone sets their code with $stc the bot would also update the pinned message. That way new users can easily find 1 message containing all codes and the command $gtc would only be used when someone requires a specific code.

alternatives you've considered**
Making the suggested pinned message myself. =P

**Comment by Qualibert** [comment]
This is just my opinion / summary:

This have been suggested before and rejected, the reason was some people don't want to be randomly added but still like to be able to give their code to fellow raiders. Being ''only'' on request, the friend code stays a ''pick and choose'' option for friend codes.

Also you'd run into issue with only one pinned post after a lot of members, you'd have to do some pagination or multiple post after you reach Discord message limit.

May I suggest using a ''bot commands'' channel for people to ''spam'' commands and not bother the others chats? Most of the servers do this, just mute this channel and you're good to go.

**Comment by H2thaP** [comment]
Thanks for your comment Qualibert! 

We do have a channel for people to solely use for commands, yet not everyone always uses it so we have to redirect them. 
As for the randomly adding part.. It would only effect the people giving the code in the first place, Why would you submit your code if you want it to remain private? PoGo will always ask if you want to become friends you still have the option to decline.

Yes, but this doesn't seem to be a seem like a problem the bot can't overcome. 

Btw, I'm not saying this option should be standard but something you can turn on and off per community. Smaller ones like ours would probably love it a lot more then a community of hundreds of active members.

**Comment by Qualibert** [comment]
As for the commands in other channel, we disable them completely in the general-chat. I don't see a benefit bigger than the drawback of having huge trainer profile in the chat room.

In our server, most of the people add friends while raiding with them, if they are in the same area it make sense for them to add them and level their friendship, same with people doing a lot of pvp or trading. Then a simple $gtc can give you that code to copy and paste. Most don't want to be flooded with invites and having to sort them out. Someone yesterday did just that on a public page and got about a hundred demands, not fun.

Also there a difference, with ''posting my code in our local 200 members Discord" and "Garry copied and pasted the list on reddit so now everyone can add our members!"

Our course, Pokenav could overcome the Discord limit, it just a little bit of extra work, I was mostly refering to your ''home-made message'' solution. And yes, a toggle would be necessary if that ever become a thing like you said bigger community would not be into that, smaller ones... questionnable, small often become big and there always the ''open up to the world list leak'' problem.

**Comment by dandesousa** [comment]
So I think in order to implement this I would have to force users to "opt-in" to public friend code sharing. Would this defeat the purpose of the request?

Even though friend codes are public, there's a presumption of "pseudo"-anonymity in that you cannot look at someone's friend code unless something finds you on the discord. Its also very obvious who is looking up all the friend codes if they leak out. Therefore any sort of server wide publishing of the friend codes would require an explicit opt in to preserve the nature of the arrangement. Also the bot is not optimized to do user lookups by server like that. It's a larger than expected change.

I also could be open to the idea of a raid command that prints every raid members friend code for the purposes of pre-friending everyone. I would probably want to run it by the Patron "brain" trust to make sure there aren't major concerns before I do any work on this.

**Comment by Kdog0073** [comment]
Unfortunately, most would never be able to understand that when you update your trainer code, it is "available but not really". I do like the raid idea a bit better because you are at least expecting to meet the requester.

**Comment by Qualibert** [comment]
I would need the raid command to show all trainer codes to be opt-in only.
 I'd be uncomfortable to allows this by default on my server and it's confirmed with a really quick survey on my server. Some are not okay with that.

**Comment by Rhendak** [comment]
I generally agree with it being a good idea to have a pinned message from the bot containing all the trainer-codes reported in the community via the `$stc` command. This pinned message should be updated by Pokénav everytime a new/changed friendcode is set within that same community. The pinned message should only include codes that are also visible within the trainer's Pokénav profile.

Qualibert imposes a good question about people who don't wish to be added and people that don't with their codes leaked.
- People that don't want to be added: in my opinion these people should not set their trainer code in their profile if they feel like this. Them not setting their trainer-code in their profile would also mean that their trainer-code wouldn't automatically get added to the pinned message. They can distribute their friend code via DM's when asked or when meeting other players in real life. 
- Codes being leaked: This is not really a problem of the pinned message suggestion. Someone could use `$gtc` for a bunch of people and get a lot of codes that way and still leak them. So codes leaking is not really a problem added by a pinned message, but an already existing one. And again if people don't want their code leaked, I suggest they don't set their trainer-code in their Pokénav profile.

**Comment by Kdog0073** [comment]
Actually another thought... players can just change their code if the list is leaked. It really isn’t something that has huge security consequences like a password. Just hit the refresh-looking button in that bottom right corner.

**Comment by H2thaP** [comment]
The suggestion of adding a command in a raid list is very nice, as stated before you would indeed see the person you'd become friends with in person. Yet the best thing of this command is that you would only add current active players. A list would become outdated at one point as people stop playing. You could of course fix this with a rule that only players active in Discord for the past x weeks would be allowed to stay in the list but I'd imagine that's quite a workload. 
As a bonus players can recognize new players that use the command in the raid channel so they can be welcomed personally in the community.
