### ISSUE TITLE
`with` command `+` syntax too permissive

### ISSUE THREAD

**Issue by dandesousa** [PokeNavBot/issue-tracker#333]
**Describe the bug**
https://cdn.discordapp.com/attachments/428184757524758528/555732087173546004/bug.jpg

**Comment by sunkast** [comment]
Here is another report of a PokeNav user with this same issue:

https://discordapp.com/channels/427476219890630656/428184932884545546/577515629909901355

**Comment by Qualibert** [comment]
Since it's a related issue, here's the problem above described: **Using + as prefix conflict with the + alias for $with**

If PokeNav prefix is set to ``+``, commands used in raid channels will fire both the command used and the ``$with`` command from the ``+`` alias. 

**Ex**:  ``+bye`` will prompt ``A trainer left the raid`` then ``A trainer have additional players with them``

PokeNav should have a safeguard against this, either by restricting the + alias to prevent two commands from firing or by rejecting ``+`` as a prefix to prevent this behavior.
