### ISSUE TITLE
Gym name should *never* be "Walk closer to interact with this Gym."

### ISSUE THREAD

**Issue by Darr247** [PokeNavBot/issue-tracker#357]
**Describe the bug**

Since PokeNav ignores the clock shown on the top line in 95% of screenshots and uses the post's timestamp instead, most users try to post as soon as possible after making the screenshot, so they usually do not inspect them full screen (and Discord's thumbnail view during attachment does not show the gym name)... so if the gym name is obscured and the user is further from the gym than about 25m, the bot sees the name of the gym as **Walk closer to interact with this Gym.** 

If PokeNav detects the name of the gym as "Walk closer to interact with this Gym." it should refuse to create the raid and give the screenshot a thumbs down reaction.

Example of obscured gym name
![Screenshot_2019-04-07-05-48-59-812](https://user-images.githubusercontent.com/1146636/55683354-be60b800-590c-11e9-9736-55f9eac6f48e.jpeg)
(many devices provide only Lock+Volume Down as the screenshot key combination.)

Example of Discord thumbnail/preview when posting screenshot
![Screenshot_20190407-074437_Discord](https://user-images.githubusercontent.com/1146636/55683381-15668d00-590d-11e9-8bdd-4cbf8934440b.jpg)
(so user cannot see that the gym name is obscured.)

Again, in my opinion, if PokeNav detects the name of the gym as "Walk closer to interact with this Gym." it should refuse to create the raid and give the screenshot a thumbs down reaction... even if it DOES still charge the user's quota because of OCR use.

Thanks.

p.s. Since this is a side-effect of Discord not showing a thumbnail of the entire screenshot when selecting it for attachment, I will also be looking to report this as a bug/feature request for Discord, too.

**Comment by dandesousa** [comment]
@Darr247 so I actually can't fix this problem **fully** in the way you are suggesting. I appreciate the time you spent to post it, and I will take time now to explain the complication of it:

The way PokeNav currently determines if something is a raid is actually multi-factored. One factor is if it detects a timestamp in the image for the raid. However, when a gym is far away on certain devices, the walk closer label will obscure the timestamp and make it unreadable (pretty much any iPhone X+). So there's a special rule that says if you can't read an end time from the screenshot and theres a distant warning label in the image, assume that its blocking the label and make the raid anyway, without any time. This is done so that the raid can be corrected later and quota isn't wasted. It's this rule that is actually letting this slip through. 

Because this rule only happens on raid bosses (not eggs) I can make it restricted further based on whether an egg is detected so this wouldn't make a raid. **But it wouldn't solve it for if they did this for bosses.** There's actually a real question about whether screenshots like this should make raids.

Sometimes the gym text just isn't readable and it reads the next line it can. I don't think a failed gym name parse is necessarily a cause for a failed scan.

I mentioned in the Patron channel that I actually have been implementing an experimental classifier that would filter out all sorts of junk, non-raid screenshots before reaching OCR, preventing quota waste. I haven't tested this particular screenshot but I actually suspect it would be filtered out by this. It would be an opt-in setting that might solve the problem. Its not going to be ready for this week, but I'll leave this comment here and see what your thoughts are.
