### ISSUE TITLE
Get-Trainer-Code by Tag

### ISSUE THREAD

**Issue by Velocitractor00** [PokeNavBot/issue-tracker#371]
**Is your feature request related to a problem? Please describe.**
as users set their trainer-code, it seems intuitive to tag them to view it, but this doesn't work (much the same as it didn't used to work with badges)

**Describe the solution you'd like**
to be able to use $gtc with a tagged username, rather than the proper english version.

**Describe alternatives you've considered**
n/a

**Additional context**
unsure of how difficult this was to implement for the badges, but as a QoL adjustment, it might be nice for the codes too.

**Comment by Qualibert** [comment]
As stated before, the fact that tags don't work for $trainer and $gtc is not a technical limitation but a decision made by IVpips. 

It's there to deter people from notifying users everytime they just want to look at a profile or get a trainer code as this action don't need user attention at all and could get annoying. Even pushing users to disable mentions notifications which could be bad for PokeNav operations.

Badge commands were granted permission to use tag because the announcement already tag the member anyway to notify them they got something new.

**Comment by Velocitractor00** [comment]
hmm, I dunno, I think if you compare it to trading its no different, the bot sends them the username and trainer-code, so I can see what you are saying about the tagging itself getting annoying, but at the same time, wouldn't you rather know when someones looked up your trainer code?

**Comment by Velocitractor00** [comment]
on the main server here we haven't made the $gtc command common knowledge tbh, but not for that reason

**Comment by Darr247** [comment]
They essentially look it up with **$profile _[username]_** if the user has filled in that info... and we aren't notified when someone runs **$profile _[our username]_**

**Comment by Velocitractor00** [comment]
yeah I know that, but it feels way more intuitive to use the tag imo

**Comment by Velocitractor00** [comment]
also, some people dont use the same nickname on every server, so if you are doing $gtc with the nick not the trainer name, it doesn't seem to work (unless they match)

**Comment by LeRaffl** [comment]
I still think this should be a thing
