### ISSUE TITLE
Button to show interest

### ISSUE THREAD

**Issue by Jomiph** [PokeNavBot/issue-tracker#392]
**Is your feature request related to a problem? Please describe.**
In our small community, attendence to a L5 raid usually only starts when someone shows interest. They don't sign up for it until they think they are enough.

**Describe the solution you'd like**
Having a button to signal "I'm interested" or "I'm available" would greatly help gather interest for a raid.

**Describe alternatives you've considered**
Right now people have to talk in our raid lobby, making it more cluttered than necesary, and detracts people from using the "join raid" function, as they think writing "i'm coming" is enough.

I believe having a fourth button under a raid would greatly improve attendence to raids, at least in smaller communities where bare minimum attendence happens a lot.

**Comment by dandesousa** [comment]
Sounds like you came from Meowth :) ? 

PokeNav currently reduces the state of membership counts to those that join, which implies you are **interested and available**, otherwise you $bye when you realize you can no longer join the raid. So in that sense there is already a button for it. Then when there are enough people, most communities `$su` with what time they are going and if others join they tag or honor the agreed time.

My recommendation would be to try and break the ice through education. It also has a side effect of moving chatter about the raids away from the lobby and into the raid party channel

**Comment by dandesousa** [comment]
One other thing I would say is that -- in a community where there's smaller number of people, you will find that everyone coordinates in the lobby, but that becomes difficult if the number of simultaneous raids grows, hence the current implementation. So this sets you guys up for growth if more raids happen, people won't have to alter their coordination strategy
