### ISSUE TITLE
Self-actualized Research summary

### ISSUE THREAD

**Issue by mikosoby** [PokeNavBot/issue-tracker#400]
**Is your feature request related to a problem? Please describe.**
The `#active-research` channel is not the best way to see all the available Research. And regulary asking the bot to list all of that using `$list q` might be a lot of spam. So a an option to have a "permanent" list of quests somewhere would be nice.

**Describe the solution you'd like**
Option the have a dedicated channel(`#research-summary`) with a "permanent" list of quests.
Everything the same as the `$list q`, but this post would be automatically actualized with new research information. So instead of regulary quering the bot for `$list q`, one would just go to the dedicated channel.

**Describe alternatives you've considered**
Place this post on top of the `#active-research` and pin it there.

**Additional options**
- This feature might be disabled.
- This dedicated post could be placed in posssible any channel and pinned there? *Might be overcomplicating things a bit.*

**Comment by TheGerontocracy** [comment]
I've jury-rigged exactly this setup on my server since day one, as a sorting of research by time reported makes little sense. My "active-research" channel consists of a link to pgmap and the output of $list q. For me, the list is just a preview of what's on the map. Whenever there's a new report my bot deletes the old list and requests a new from pokenav. 

This only makes sense when there are a limited number of reports, though. Not sure how much resources it consumes on the pokenav side and I'm not going to scan a 100 line list looking for a stop nearby. My ideal setup would be a list with the number of quests for each type and a link to pgmap.

**Comment by mikosoby** [comment]
bump

**Comment by mikosoby** [comment]
bump

**Comment by mikosoby** [comment]
BUMP!
