### ISSUE TITLE
Change reactions for screenshot scanning

### ISSUE THREAD

**Issue by craigjm79** [PokeNavBot/issue-tracker#403]
**Is your feature request related to a problem? Please describe.**
We have several town raid chats, and have configured PokeNav to use those as raid-lobby channels. We have toggled off create-raid-channels, as people in different towns are used to coordinating raids in their town channels. Sometimes people post raids with just a text message, other times with the nearby raids screen, and other times with a gym screenshot. We wanted to use PokeNav to help with those gym screenshot occasions, and let the other methods keep taking place. Unfortunately, some people are offended when PokeNav thumbs downs their screenshots that are not gym screenshots. We would like to change the reaction to something more neutral. Ideally we could just configure the reactions PokeNav uses.. We know it still eats up our quota, but we're bothered by that.

**Describe the solution you'd like**
We would like to be able to choose which reactions PokeNav uses to change them to something other than thumbsup and thumbsdown.

**Describe alternatives you've considered**
We've thought about finding a bot to remove the reactions, or post a message after PokeNav reacts to explain the thumbsdown, but have not had any luck. We have considered using #announce-raids-here as the only place screenshots are processed, but then people would not get a raid card in their town chat, and it would split up raid coordination, or more likely, would just be unused while people coordinate in their town chat channels. Creating raid channels for each raid was also considered, but was too complicated for our users in our testing.

**Additional context**
<img width="278" alt="thumbsdown_nearby" src="https://user-images.githubusercontent.com/51716904/59293167-a24eff00-8c4c-11e9-9c15-9390d92b54bb.png">

**Comment by TheGerontocracy** [comment]
Not sure this is an option for you, but it would be really easy to make a tiny bot just for removing the thumbsdown reaction. If you have someone who knows a bit of programming, something like this would do the trick (Python, not tested): 
`import discord

token = 'your-bots-token'

client = discord.Client()

@client.event
asyn def on_reaction_add(reaction, user):
    if reaction == '👎' and user.display_name == 'PokeNav':
        await reaction.message.remove_reaction('👎', user)
        
client.run(token)
`

**Comment by craigjm79** [comment]
That's definitely something I'll look at testing. My only real issue with that is I have nowhere to run the bot full time, but it's possible I could find a home for it. Hopefully I can give that a shot later this month.

**Comment by dandesousa** [comment]
@craigjm79 sorry I've been backlogged between go fest and others but here's my response:

I have a couple work arounds for you, since this seems server specific:

1. @TheGerontocracy suggestion is a good one, if you can put a bot together that'll do it.

2. You can also add Atlas to your discord https://atlasbot.xyz -- they are hosted for you and does a lot of custom stuff configurable through a dashboard. Specifically -- you can have a PokeNav thumbs down reaction post a message explaining that its rejected the screenshot. (I've included a screenshot of how that might be setup, just check the reaction to the one you want explained) -- Atlas devs might even be able to add a the remove reaction functionality if it doesn't exist (just ask in their discord).

3. Atlas might have some features for limiting reactions in certain rooms. PokeNav doesn't care about the reaction being removed after its tried to do it -- so its perfectly safe to remove it.

![Screen Shot 2019-06-22 at 9 27 38 AM](https://user-images.githubusercontent.com/3880281/59964528-16e92f80-94d0-11e9-9f86-7e09a8ba3e2a.png)

If none of these end up helping please tag me in here again and I'll re-open it and see if any other users have a similar request and if they do look towards doing the feature. For now I will close it.
