### ISSUE TITLE
Raid-channel named by Alias

### ISSUE THREAD

**Issue by dzygit** [PokeNavBot/issue-tracker#443]
**Is your feature request related to a problem? Please describe.**
Theres a lot of similar named gym when we add a ss name of raid channel are awful ...
like:
Legionowo Plac zabaw z kolorom płotkiem 
Legionowo Plac zabaw z konikami

**Describe the solution you'd like**
We can make gym in POI its awesome! SS match to direction - we can add alias, and here we have a solution. When ss is match with poi we colud use alis as name of raid-channel
example:
Legionowo Plac zabaw z kolorom płotkiem 
alias: kolorowy-plotek

**Describe alternatives you've considered**
I try to manual changing of chanel but you know.. ;)

**Comment by Qualibert** [comment]
It could be useful, but would also need a way to choose which alias should be used:
- Some admins use aliases to compensate for common OCR misreadings, which would not be ideal as a channel name.
- You can add multiple aliases for each POI, not only one.

**Comment by Kdog0073** [comment]
I had actually requested this too in https://github.com/PokeNavBot/issue-tracker/issues/295. The pokemon side was partly resolved since ex raids now are prefixed with just "ex".

My recommendation would be that instead of picking from the aliases, have a separate "channel-alias" or "nickname" field (and ofc all corresponding commands).

**Comment by Kdog0073** [comment]
#437

**Comment by dandesousa** [comment]
I think the simplest path forward is to allow a single alias to be marked as the nickname and it is used in place of the name for most display purposes.
