### ISSUE TITLE
List ex eligible gyms

### ISSUE THREAD

**Issue by sunkast** [PokeNavBot/issue-tracker#450]
Might be kind of neat to be able to list all ex eligible gyms. Could be as simple as $gi ex-eligible to get a list.

**Comment by mikosoby** [comment]
Wouldn't the `$show ex-eligible-gyms` be better with the current naming convention?

Still, supporting the idea a lot.

**Comment by LegendRed01** [comment]
At the Moment we have something like` $list routes` so why not `$list ex-eligible-gyms`

**Comment by typographynerd** [comment]
Additional feature would be able to use the reported EX-raids to indicate that they had a recent EX raid, so they wouldn't be eligible for the following week.

**Comment by dandesousa** [comment]
@typographynerd this shouldn’t be necessary since ex eligible gyms are blocked and don’t have any raids when a pass is out. If they have raids they could trigger. Presumably the list exists to show you which gyms are marked so you can fill in the gaps. Though the presence a raid there could still be marked in the list it would have to be separate ticket from this one which i meant to close already.
