### ISSUE TITLE
Notify-roles intermittently not tagging 

### ISSUE THREAD

**Issue by M3G4N5** [PokeNavBot/issue-tracker#455]
**Describe the bug**
When raid bosses are updated, notify-roles are intermittently not notifying. No identifiable pattern. 

**To Reproduce**
Has been observed on manual command raid entries where the egg has been previously reported, e.g.
$egg 1 gymname 59, followed later on hatch by (e.g.)
$raid squirtle gymname 44 

**Expected behavior**
Notify-role should tag once boss has been updated

**Comment by dandesousa** [comment]
@M3G4N5 sorry for the delay in getting back to this -- finally sitting down to do it and wanted to follow up.

I'm having trouble re-producing this. How easily does it get reproduced on your server? Things I've tried:

- Makes subs with three boss rules in it
- Announcing a raid with $r/$egg then updating it via another command
- Announcing a raid with $r/$egg then when it hatches updating it.
- Updating it via dm
- Updating it via channel

Every time I get the duplicate raid ongoing and it updates the raid and gives me the notification.

If its something reliable then it might easier to see what is happening on your server. If you have a raid that occurred that you recall doing it you can also post a screenshot of your raid and the time it updated / created so I can look at the logs.

Most likely possibility is some internal error occurs and it skips notifying rules

**Comment by M3G4N5** [comment]
Hi Dan

Sorry just saw this, I’ll try to grab some specific examples/screenshots
tomorrow during raid hours.

Cheers, M

**Comment by swanny246** [comment]
Hey, I believe I have found the root cause of the issue. The issue occurs when the raid boss is updated before the posted hatch time on the raid egg.

Sometimes the posted hatch time is off by a minute or so, and when the raid boss hatches, and users go to update the raid boss, the message updates to "<Boss> hatches at <despawn time>" instead of "<Boss> until <despawn time>". When this happens, the notify tag isn't sent.

Demonstrated below in a test lobby (using really extreme out of time sync examples to ensure the issue occurs)

![image](https://user-images.githubusercontent.com/8400291/72879564-e1980f00-3d48-11ea-8124-d5ac4c6a6259.png)

![image](https://user-images.githubusercontent.com/8400291/72879602-fa082980-3d48-11ea-9e63-a39410ea1539.png)

![image](https://user-images.githubusercontent.com/8400291/72879623-02f8fb00-3d49-11ea-834d-81437d2b04c7.png)
