### ISSUE TITLE
Investigating Gym names without quotes in $raid command?

### ISSUE THREAD

**Issue by dandesousa** [PokeNavBot/issue-tracker#60]

**Comment by cykopat** [comment]
Another option to look at this is use "," as a delimiter between commands. 

For Example. 

$r Pokemon, St Luke Union Church, 44
Command Pokemon, Gym Name, Time Remaining 

I would think the "," is quicker to select than than " on most phones.

**Comment by arincewind** [comment]
I don't see that any punctuation is needed. Meowth bot works fine using !raid 4 my gym name 45 or !raid flareon my gym name 45.
Simple enough to parse, the last word is numerical the first word either matches a Pokemon name or is numerical all words in-between is the gym name.

**Comment by fortepc** [comment]
But what if the gym name has numbers after "cafe 57" for example is a gym
near me.

**Comment by fortepc** [comment]
Considering this but actual recognizes the gym name, and provides
navigation to it, getting the gym name right is pretty important... So at
the very least punctuation separation should be a fall back to force a
numeric gym name.

**Comment by arincewind** [comment]
So
 $raid flareon cafe 57 57
should create a raid that ends in 57 minutes for a gym called 'cafe 57'.

**Comment by dandesousa** [comment]
@arincewind Meowth and PokeNav raid commands do not do the same thing so comparing them is apples and oranges. Not requiring quotes just requires custom parsing of the command.

PokeNav lets you create a raid without any structure at all. If you don't care about the times or gym and just want a coordination room, you can do:

`$raid at the firehouse registeel egg popping in 15 minutes`

It will make a room for registeel with a standard raid expiration timer of 1:45 (no hatch and despawn timers or gym info) and the attributes can be corrected later but mostly people don't care. Its still used and useful for people who do multi-gym raid trains.  Most new users don't know this and aren't familiar but the ability to create a room without fail and reasonable defaults is what would have to be sacrificed to get no quotes working, otherwise theres too many possible misinterpretations.

The alternative is to move the old behavior to a different command and do strict enforcement or vice versa.

**Comment by dandesousa** [comment]
@arincewind also its impossible to know that if you do `$raid flareon cafe 57` that you meant cafe 57 or the gym `cafe` with 57 minutes left.

**Comment by dandesousa** [comment]
I know people would rather not use quotes but there will be ambiguities as a result if implemented, just fyi.

Theres a reason every command line interface ever developed requires escaping of delimited characters or quoting.

**Comment by cykopat** [comment]
Having the Gym and Stop Database a huge a positive. So there is a possibly that you could have a future state that turns the command into a two step process process. 

Step 1. Issue command with Pokémon and gym. 
Step 2. Bot response I’ve matched the gym or did you mean list of close matching name. React with number. 
Step 3. Bot responds to choice and says “ok great, finally when does it despawn? Enter Minutes: 

Ok so it’s 3 steps. Now this doesn’t exist yet and it would require each discord to ensure they setup their coordinates and probably a check when installing PokeNav if there is a gym dB loaded for the area 

Perhaps an even easier method is a server toggle for Expert Mode or Tutorial Mode. 

If tutorial mode. 
1. $raid machamp
Response: What gym?
2. Type in gym name
Response: great matches gym name, when does it despawn?
3. 34
Response: Creating Party and despawns in 34 minutes. 

The quotes are “the mobile discord client killer” to lots of people. For us at The Go Group we have  two of us that has sponsor level to ensure we have the option for OCR or our users. 

We used Meowth for a very long time. So all my suggestions of course came full of confirmation bias because of what I was used to. 

What I’ve suggested here is I’m sure a ton of work for IVpips. I am not lost on the fact that by labeling steps 1-3 that probably during the conversion from “simple steps” to Dev hours is insane. 

It’s a user benefit analysis really. If users don’t like the quotes, then use both bots. Meowth for Text reporting and keep PokeNav for advanced reporting. Sure you will have different channels for output and you will miss out on the active-Raids channel. However it all comes down to the larger benefit gained. 

Shift your perspective: 
- Can you create a role for people who want to clean up the reported raids? When they don’t use quotes? 
- Can you encourage screen shots

Anyways.. now that I wrote it above I kinda like the novel idea that you don’t have to fit the entire report into one delimited message and have the bot walk you through it. Idk. 

Or just hold back and wait for the App because that feature alone will be a huge marketing point to your users. 

Just my 2 lazy cents on a Sunday. 

Side Note: on IOS I don’t even open discord to report Raids. Screen Shot, open screen shot, tap share icon, choose discord and send. Delete screen shot and move on. We won’t be going back to meowth just because of that. Lol

**Comment by SquirePug** [comment]
We just had this discussion internally about why Meowth handles this better than Pokenav. Basically we just assume that Meowth took the last variable of the text split as time, and the first variable as type, and mung the rest together as "gym name".

e.g. 
![image](https://user-images.githubusercontent.com/42793435/46521928-7e206e80-c8c4-11e8-9e43-5ec08799a5b0.png)

Given how heavily used Meowth is, I do not see their being huge downsides to this method. There is the edge case of someone reporting a Raid with no time, and the gym name ending in a numeral, but this seems to be a very small minority of use cases.

Also this could be resolved with the implementation of assignable aliases to Gyms.

**Comment by dandesousa** [comment]
Aside from the legacy stuff mentioned in https://github.com/PokeNavBot/PokeNav/issues/60#issuecomment-408702328

Meowth and PokeNav are different because the **feature sets for raids are different**. PokeNav gracefully defaults missing information and does gym matching by default. This isn't changing because its used by too many people. Specifying the long form is the minority use case by far and "tedious" way to do it, yet we are discussing removing 2 characters from a 20-30 character command syntax and introducing ambiguity as a result. 

Consider a gym called `Soldiers of World War 2`. It is literally impossible to determine in "Meowth" mode if you meant Gym = `Soldiers of World War 2` with no time specified or Gym = `Soldiers of World War` with Time = `2 minutes`. This basically makes it impossible to announce a raid at that gym without a time. This matters in PokeNav because missing information is defaulted and can be filled in later. This will never change.

Also there are so many alternatives. Screenshots "just work" ™️, the app may soon alleviate this as well and in discord the real solution here is gym aliases, since they can be made into one word and shorten the command syntax significantly, (quotes optional for a single word, only required to escape multiple word gym names).

Barring that the only other solution would be a different raid command that doesn't support free form text and defaulting.

**Comment by dandesousa** [comment]
Going to close this because aliases now exist and alleviate the need for this.
