### ISSUE TITLE
Allow role "raid moderator" to use mi

### ISSUE THREAD

**Issue by ukbigdave** [PokeNavBot/Issue-Tracker#619]
**Is your feature request related to a problem? Please describe.**
Raid moderators can use a number of the hosting commands (go/bo/end). 

**Describe the solution you'd like**
I think allowing the mods to use $mi will support with raid lobbies. 

**Describe alternatives you've considered**
Training. 

**Additional context**
N/a.

**Comment by FlipsCat** [comment]
how much more benefit would this be though? our mods type $mi and then the host replicates?

**Comment by ukbigdave** [comment]
You could say same for go/mm/end ect.  If a raid mod can use some host raid functions, why not all? (mi  was a later addition). Some hosts will not use mi, so us doing it is an additional assistance to newbies/show them what it does. What's the harm in it?

**Comment by dandesousa** [comment]
`mi` stands for `my-invites`. in a regular raid **anyone** can use `mi`, in a remote raid the raid moderator has no invites so they cannot use `mi` unless they are the host. So this would only work for remote raids but the behavior would be silently different in standard raids and potentially confusing.

Edge cases like this make the bot more complicated and make it harder to maintain this feature if we add multi-host option to remote raids or decide to change it in some other related way. TBH I did make commands more flexible like this in the past but am no longer inclined to do so due to how complex things like the `raid` command have become (where it every conceivable way to specify the arguments yet doesn't set things subtly if wrong and makes it really hard to change anything and keep all the features in tact).

Additionally, there would have to be utility to change the behavior beyond just instructional. You can tell them to type `$mi` or `$go` to get the raid list and after they do it the first time they won't forget. The other raid moderation commands can have utility for cleaning up or fixing broken raid channels quickly. 

I'm open to reconsidering this in the future, but I have to triage issues carefully since people request things faster than I can add them to the bot.

Thanks for the suggestion.
