### ISSUE TITLE
Server disable of Sub

### ISSUE THREAD

**Issue by ukbigdave** [PokeNavBot/Issue-Tracker#646]
**Is your feature request related to a problem? Please describe.**
We have had people spam us with 'sub' in raid channels. Not sure where they learned from. Most Pokenav servers I visit have reaction roles, not users using sub

**Describe the solution you'd like**
Parameter to disable sub, and subs for normal players in normal channels. 

**Describe alternatives you've considered**

**Additional context**

**Comment by dandesousa** [comment]
This sadly isn't really a solution for spam, instead #139 is the ticket for this. If its not `sub` it'll be something else (`profile`, `counters`, etc)

**Comment by Loony2go** [comment]
or maybe $counters can be pmd to them instead of posted in the raid channel. and $profile should be blocked from being used in raid lobby channels. Im curious are you saying they are subscribing to raids or raid notifications in the raid channels? What do you mean by normal players? Do you mean not remote players? what I do is just add pokenav role to the channel and then block pokenav by restricting all and any permissions in any raid chat channels that are not bot announce raid channels or bot private raid lobby channels or bot active raid channels
